package org.labor.pojos;

// Generated Jul 26, 2013 2:30:51 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Employer generated by hbm2java
 */
@Entity
@Table(name = "Employer", catalog = "tempit")
public class Employer implements java.io.Serializable {

	private Integer employerId;
	private String accountId;

	public Employer() {
	}

	public Employer(String accountId) {
		this.accountId = accountId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "employer_id", unique = true, nullable = false)
	public Integer getEmployerId() {
		return this.employerId;
	}

	public void setEmployerId(Integer employerId) {
		this.employerId = employerId;
	}

	@Column(name = "account_id", length = 4096)
	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

}
