package org.labor.pojos;

// Generated Jul 26, 2013 2:30:51 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EmployerToJob generated by hbm2java
 */
@Entity
@Table(name = "Employer_to_Job", catalog = "tempit")
public class EmployerToJob implements java.io.Serializable {

	private Integer id;
	private Integer employerId;
	private Integer jobId;

	public EmployerToJob() {
	}

	public EmployerToJob(Integer employerId, Integer jobId) {
		this.employerId = employerId;
		this.jobId = jobId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "employer_id")
	public Integer getEmployerId() {
		return this.employerId;
	}

	public void setEmployerId(Integer employerId) {
		this.employerId = employerId;
	}

	@Column(name = "job_id")
	public Integer getJobId() {
		return this.jobId;
	}

	public void setJobId(Integer jobId) {
		this.jobId = jobId;
	}

}
