package org.labor.daos;

// Generated Jul 26, 2013 2:30:51 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Job generated by hbm2java
 */
@Entity
@Table(name = "Job", catalog = "tempit")
public class Job implements java.io.Serializable {

	private Integer jobId;
	private Date beginTime;
	private Date endTime;
	private String description;
	private String perks;
	private String location;
	private Float fee;
	private Integer employerId;

	public Job() {
	}

	public Job(Date beginTime, Date endTime) {
		this.beginTime = beginTime;
		this.endTime = endTime;
	}

	public Job(Date beginTime, Date endTime, String description, String perks,
			String location, Float fee, Integer employerId) {
		this.beginTime = beginTime;
		this.endTime = endTime;
		this.description = description;
		this.perks = perks;
		this.location = location;
		this.fee = fee;
		this.employerId = employerId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "job_id", unique = true, nullable = false)
	public Integer getJobId() {
		return this.jobId;
	}

	public void setJobId(Integer jobId) {
		this.jobId = jobId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "begin_time", nullable = false, length = 0)
	public Date getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(Date beginTime) {
		this.beginTime = beginTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_time", nullable = false, length = 0)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "description", length = 4096)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "perks", length = 4096)
	public String getPerks() {
		return this.perks;
	}

	public void setPerks(String perks) {
		this.perks = perks;
	}

	@Column(name = "location", length = 4096)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "fee", precision = 12, scale = 0)
	public Float getFee() {
		return this.fee;
	}

	public void setFee(Float fee) {
		this.fee = fee;
	}

	@Column(name = "employer_id")
	public Integer getEmployerId() {
		return this.employerId;
	}

	public void setEmployerId(Integer employerId) {
		this.employerId = employerId;
	}

}
